### ISSUE TITLE
Can't start a new project

### ISSUE THREAD

**Issue by CyberNoble** [aws/lumberyard#487]
Hello from Russia.
**Describe the bug**
I'm started with team the game project and get some problem with creating new project such as 
![1](https://user-images.githubusercontent.com/55918004/80338034-97618500-8885-11ea-9e05-a7935bb9ab02.png)
![2](https://user-images.githubusercontent.com/55918004/80338042-9c263900-8885-11ea-8920-0acb216cf51c.png)

**Steps to reproduce**

Installed the Lumberyard 1.23.1.0 Version of Lumberyard from the Lumberyard website
Installed all the required packages. See screenshots below:
Launched Project Configurator 1.23.1.0
Selected Create New
Entered the "Name" and then selected default (I've also tried this with "Empty". Note: at first I received errors "lumberyard error executing waf",cause i think that i can use vs2019 instead of 2017.After that i install 2017 and problem was disappear.But now i can't launch via engine my project.I see that problem in gems but i don't know hot to fix it
**Screenshots/Logs**

![5](https://user-images.githubusercontent.com/55918004/80337206-86177900-8883-11ea-9446-520b8fc5bba1.png)
i was try to do some stuff from same problems that i can find such as run 
"C:\GameDev\Lumberyard\1.23.1.0\dev\Solutions\LumberyardSDK_vs15.sln"
and get this 
![6](https://user-images.githubusercontent.com/55918004/80337586-72204700-8884-11ea-937c-8f7546483a28.png)
![7](https://user-images.githubusercontent.com/55918004/80337591-73ea0a80-8884-11ea-86c7-bfb16fe4e6ff.png)
![8](https://user-images.githubusercontent.com/55918004/80337594-75b3ce00-8884-11ea-99ca-5f887f693099.png)
![9](https://user-images.githubusercontent.com/55918004/80337598-76e4fb00-8884-11ea-9069-4b4f482ecbf3.png)

then i try to rebuilt project with 
![image](https://user-images.githubusercontent.com/55918004/80337619-895f3480-8884-11ea-9eca-f366ed1449c5.png)

and 
![image](https://user-images.githubusercontent.com/55918004/80338408-70f01980-8886-11ea-8e3d-89e8f6fc9b6e.png)

then got this

![1](https://user-images.githubusercontent.com/55918004/80337172-713ae580-8883-11ea-97b6-12c8cc3ba3d0.png)
![2](https://user-images.githubusercontent.com/55918004/80337184-75ff9980-8883-11ea-9c30-4d739dd660dc.png)
![3](https://user-images.githubusercontent.com/55918004/80337188-7861f380-8883-11ea-86f2-6f3036ba16b0.png)
![4](https://user-images.githubusercontent.com/55918004/80337191-7a2bb700-8883-11ea-9e0c-52c916b22fc8.png)

**Lumberyard version**
1.23.1.0

And that i have
![image](https://user-images.githubusercontent.com/55918004/80337697-ba3f6980-8884-11ea-8d3b-b8e7f7b1ab67.png)

![image](https://user-images.githubusercontent.com/55918004/80337758-e3f89080-8884-11ea-9c28-33b8e948060e.png)

![image](https://user-images.githubusercontent.com/55918004/80337766-e8bd4480-8884-11ea-93a9-c8545bc8da7f.png)
and RAM 16Gb DDR 4 2.4Mgz

Engine is placed on SSD with more than 200Gb free space,btw have HDD with 700Gb free

**What is your role in game development?**
Programmer in my own gamedev team

**Tell us about your project or studio.**
We are students and want to make our RPG.We are choose as engine Amazon Lumberyard cause it have many pros such as MMO,Graphic,fees,AWS and main is source code so let us to rebuild it in the future to make our version of engine without expensive fees.But it a more diffecult than Unity or UE4,but more interesting and give much more experience

**Comment by joshbeacham** [comment]
Your errors show that you have the video playback gem enabled, but it is unable to locate LibAV. As a result, the build fails, and as a result the video playback gem is not built. 

When you try to launch the editor, it launches the Asset Processor, and the Asset Processor cannot find the dll for the video playback gem and exits. The editor can see the Asset Processor is not running and gives you the error that it cannot initialize because the Asset Processor is not running.

To resolve the issue, you need to install LibAV and rebuild.

You can find notes on installing LibAV here: https://docs.aws.amazon.com/lumberyard/latest/userguide/component-videoplayback.html#install-libav

Specifically note, you must install the release-lgpl build. After correctly installing LibAV, avcodec.h should exist at the following path. 

`C:\gamedev\lumberyard\1.23.1.0\3rdParty\libav\11.7\usr\include\libavcodec\avcodec.h`


I also noticed in your errors that your visual studio build profile didn't match your command line profile. You'll want to switch that one as well. 

This shows **profile game**
![image](https://user-images.githubusercontent.com/1560973/80373752-8bfd6200-8863-11ea-89f1-c7e2968cd1d7.png)

While this shows **debug dedicated**
![image](https://user-images.githubusercontent.com/1560973/80373610-4f316b00-8863-11ea-8691-64300f56fc4b.png)

You can change the build profile in visual studio with this dropdown in the top left corner so that it shows the build profile you want to build.
![image](https://user-images.githubusercontent.com/1560973/80373160-a256ee00-8862-11ea-9014-ec0fe9751d18.png)
