### ISSUE TITLE
What is the status of Linux support?

### ISSUE THREAD

**Issue by UltraBurstXD** [aws/lumberyard#545]
Hi,

I want to try this marvelous GE, but I'm unsure about certain things... First I want to know if the games made with the GE can be deployed outside AWS's reach. But, what is the current status of Linux support above all?

**Comment by AMZN-Gene** [comment]
Hi! This FAQ should help with any licensing questions.
https://aws.amazon.com/lumberyard/faq/

Basically, Lumberyard can be deployed without using AWS, for instance, if your game doesn't use any cloud features, then you can ship without using AWS. If you do end up using web services then it's required you either use AWS or use your own servers, but you're not allowed to use alternate web service made by other companies.

As for Linux support, I hope these docs help.
https://docs.aws.amazon.com/lumberyard/latest/userguide/linux-intro.html
https://docs.aws.amazon.com/lumberyard/latest/userguide/linux-build-lumberyard-executable.html

The editor itself doesn't run on Linux, but using Linux for building/running the dedicated server is possible and highly recommended :)

**Comment by UltraBurstXD** [comment]
But if the editor is written in Qt, why doesn't it run on Linux? Well the project is promissory, but that issue is undesirable. We Linux folks don't like Windows too much.

**Comment by AMZN-Gene** [comment]
Good question about running the Editor on Linux.  While it’s technically possible since the source code is made available it would require quite a bit of work... this thread explains more in detail:
 https://forums.awsgametech.com/t/lumberyard-editor-on-linux/951
It’s great having feedback regarding wanting Editor for Linux; that would be really cool.  Hearing from customers ultimately helps define our roadmap so I’ll make sure to pass your suggestion along to the Editor team 👍

**Comment by UltraBurstXD** [comment]
There are many indie devs and small companies using Linux distros, and I can tell that if our games make some profit, we'd likely be happy to share our revenue by using AWS.

Unix systems are very cool for programming...
